# Generated by Django 3.2.7 on 2021-10-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('chat_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('cur_state', models.TextField(blank=True, null=True)),
                ('in_progress', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='greeting',
            name='when',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
